import express from "express";
const app = express();
app.use(express.json());
import getUserFromToken from "./middleware/getUserFromToken.js";
import usersRouter from "./api/users.js";
import productRouter from "./api/products.js";
import ordersRouter from "./api/orders.js";
app.use(getUserFromToken);
app.use("/users", usersRouter);
app.use("/products", productRouter);
app.use("/orders", ordersRouter);
export default app;
